name: Lint & Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.9"]

        env:
            USING_COVERAGE: "3.9"

        steps:
            - name: Checkout sources
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run:  |
                  python -m pip install --upgrade pip
                  python -m pip install mccabe flake8 pyflakes mypy pylint \
                      hypothesis pytest coverage black

            - name: Lint and test
              # run:  python -m tox
              run:  |
                  # Format code
                  black calculator

                  # Check code and style
                  flake8 calculator
                  pyflakes -V calculator
                  mypy  calculator
                  pylint --verbose calculator

                  # Unit test and report coverage
                  coverage erase
                  coverage run --include=calculator/* -m pytest -ra \
                              --doctest-modules --doctest-continue-on-failure
                  coverage report -m
                  coverage xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              if: contains(env.USING_COVERAGE, matrix.python-version)
              with:
                  fail_ci_if_error: no
                  verbose: true
